### ISSUE TITLE
Can 3090 with 24G memory run your code?

### ISSUE THREAD

**Issue by liuzywen** [heitorrapela/ModTr#2]
Thank you for your code. Please provide the GPU demand to run your code.

**Comment by heitorrapela** [comment]
Hello @liuzywen, thanks for your interest in our work. All our models reported in the paper were trained using a single A100-SXM4 40GB for a batch of 8 for both LLVIP and FLIR datasets.

For the larger translator (batch 8), this is what it will need more or less:
(LLVIP) 30305MiB out of 40960MiB (Input batch: torch.Size([8, 3, 1024, 1280]))
(FLIR)   16959MiB out of 40960MiB (Input batch: torch.Size([8, 3, 512, 640]))

However, there are some hparameters that can further decrease the GPU memory demand: batch size, translator size, and img input size.

Let me know if you have any additional questions. Best regards.
